### ISSUE TITLE
does not build with last version of sphinxcontrib.applehelp

### ISSUE THREAD

**Issue by LennyLip** [ninemoreminutes/xapian-bindings#10]
```
 Collecting xapian-bindings==0.1.0
#14 157.9   Downloading xapian-bindings-0.1.0.tar.gz (4.5 kB)
#14 157.9   Preparing metadata (setup.py): started
#14 170.1   Preparing metadata (setup.py): finished with status 'error'
#14 170.1   error: subprocess-exited-with-error
#14 170.1   
#14 170.1   × python setup.py egg_info did not run successfully.
#14 170.1   │ exit code: 1
#14 170.1   ╰─> [14 lines of output]
#14 170.1       Traceback (most recent call last):
#14 170.1         File "<string>", line 2, in <module>
#14 170.1         File "<pip-setuptools-caller>", line 34, in <module>
#14 170.1         File "/tmp/pip-install-2pm03nl9/xapian-bindings_0865e2bbebba44cbb7bef61b39c7c97e/setup.py", line 333, in <module>
#14 170.1           setup(
#14 170.1         File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
#14 170.1           _install_setup_requires(attrs)
#14 170.1         File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
#14 170.1           dist.fetch_build_eggs(dist.setup_requires)
#14 170.1         File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
#14 170.1           resolved_dists = pkg_resources.working_set.resolve(
#14 170.1         File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
#14 170.1           raise VersionConflict(dist, req).with_context(dependent_req)
```

`pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-v55i4vfp/xapian-bindings_81a699d97e7443a98a5d8c2f5e3aa4c7/.eggs/sphinxcontrib.applehelp-1.0.3-py3.10.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})`

**Comment by ajslater** [comment]
This seems to have been some local config issue. Seems to have resolved as of two weeks ago.

**Comment by ajslater** [comment]
I'm also seeing this. Don't have a workaround yet.

**Comment by ajslater** [comment]
Looks like this is the cause https://github.com/sphinx-doc/sphinx/issues/11130
The actual issue is upstream with sphinx and their recent release flurry.

**Comment by ajslater** [comment]
I experimented with forking xapian-bindings and pinning the sphinx dependency to an old version, but never got it to work. It always tried to get he latest sphinxcontrib.applehelp and I never tracked down why. I've since switched to Whoosh.

**Comment by LennyLip** [comment]
> I experimented with forking xapian-bindings and pinning the sphinx dependency to an old version, but never got it to work. It always tried to get he latest sphinxcontrib.applehelp and I never tracked down why. I've since switched to Whoosh.

I install (docker) dependencies packages before xapian-bindings installs in requirements.txt:

```
RUN pip install sphinxcontrib-applehelp==1.0.2 sphinxcontrib-serializinghtml sphinxcontrib-devhelp sphinxcontrib-htmlhelp sphinxcontrib-jsmath sphinxcontrib-qthelp
RUN pip install --no-cache-dir -r requirements.txt
```

So, it works for me now.
