### ISSUE TITLE
does not build with python 3.11

### ISSUE THREAD

**Issue by ajslater** [ninemoreminutes/xapian-bindings#7]
tried to install xapian-bindings on the python3.11.0-alpine3.16 docker image.
https://hub.docker.com/_/python

installs fine on the python3.10.8-alpine.3.16 docker image.

however build fails with:
```ModuleNotFoundError: No module named '_xapian'``` at some point

it also complains during configure that the imp module is deprecated in favor of importlib, but i'm not sure that's really a cause of failure. This part will break in python 3.12, however.

build log appended:

```
#0 112.0     × Building wheel for xapian-bindings (pyproject.toml) did not run successfully.
#0 112.0     │ exit code: 1
#0 112.0     ╰─> [310 lines of output]
#0 112.0         running bdist_wheel
#0 112.0         running xapian_config
#0 112.0         /usr/bin/xapian-config
#0 112.0         1.4.19
#0 112.0         running build
#0 112.0         running build_py
#0 112.0         creating build
#0 112.0         creating build/lib
#0 112.0         creating build/lib/xapian
#0 112.0         copying xapian/bindings.py -> build/lib/xapian
#0 112.0         running egg_info
#0 112.0         writing xapian_bindings.egg-info/PKG-INFO
#0 112.0         writing dependency_links to xapian_bindings.egg-info/dependency_links.txt
#0 112.0         writing top-level names to xapian_bindings.egg-info/top_level.txt
#0 112.0         reading manifest file 'xapian_bindings.egg-info/SOURCES.txt'
#0 112.0         reading manifest template 'MANIFEST.in'
#0 112.0         writing manifest file 'xapian_bindings.egg-info/SOURCES.txt'
#0 112.0         installing to build/bdist.linux-x86_64/wheel
#0 112.0         running install
#0 112.0         running install_lib
#0 112.0         creating build/bdist.linux-x86_64
#0 112.0         creating build/bdist.linux-x86_64/wheel
#0 112.0         creating build/bdist.linux-x86_64/wheel/xapian_bindings-0.1.0-1.4.19.data
#0 112.0         creating build/bdist.linux-x86_64/wheel/xapian_bindings-0.1.0-1.4.19.data/purelib
#0 112.0         creating build/bdist.linux-x86_64/wheel/xapian_bindings-0.1.0-1.4.19.data/purelib/xapian
#0 112.0         copying build/lib/xapian/bindings.py -> build/bdist.linux-x86_64/wheel/xapian_bindings-0.1.0-1.4.19.data/purelib/xapian
#0 112.0         running install_egg_info
#0 112.0         Copying xapian_bindings.egg-info to build/bdist.linux-x86_64/wheel/xapian_bindings-0.1.0-1.4.19.data/purelib/xapian_bindings-0.1.0-py3.11.egg-info
#0 112.0         running install_scripts
#0 112.0         running xapian_install
#0 112.0         running xapian_build
#0 112.0         running xapian_extract
#0 112.0         running xapian_download
#0 112.0         checking for a BSD-compatible install... /usr/bin/install -c
#0 112.0         checking whether build environment is sane... yes
#0 112.0         checking for a thread-safe mkdir -p... ./install-sh -c -d
#0 112.0         checking for gawk... no
#0 112.0         checking for mawk... no
#0 112.0         checking for nawk... no
#0 112.0         checking for awk... awk
#0 112.0         checking whether make sets $(MAKE)... yes
#0 112.0         checking whether make supports nested variables... yes
#0 112.0         checking whether UID '0' is supported by ustar format... yes
#0 112.0         checking whether GID '0' is supported by ustar format... yes
#0 112.0         checking how to create a ustar tar archive... none
#0 112.0         checking build system type... x86_64-pc-linux-musl
#0 112.0         checking host system type... x86_64-pc-linux-musl
#0 112.0         checking how to print strings... printf
#0 112.0         checking for style of include used by make... GNU
#0 112.0         checking for gcc... gcc
#0 112.0         checking whether the C compiler works... yes
#0 112.0         checking for C compiler default output file name... a.out
#0 112.0         checking for suffix of executables...
#0 112.0         checking whether we are cross compiling... no
#0 112.0         checking for suffix of object files... o
#0 112.0         checking whether we are using the GNU C compiler... yes
#0 112.0         checking whether gcc accepts -g... yes
#0 112.0         checking for gcc option to accept ISO C89... none needed
#0 112.0         checking whether gcc understands -c and -o together... yes
#0 112.0         checking dependency style of gcc... gcc3
#0 112.0         checking for a sed that does not truncate output... /bin/sed
#0 112.0         checking for grep that handles long lines and -e... /bin/grep
#0 112.0         checking for egrep... /bin/grep -E
#0 112.0         checking for fgrep... /bin/grep -F
#0 112.0         checking for ld used by gcc... /usr/x86_64-alpine-linux-musl/bin/ld
#0 112.0         checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
#0 112.0         checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
#0 112.0         checking the name lister (/usr/bin/nm -B) interface... BSD nm
#0 112.0         checking whether ln -s works... yes
#0 112.0         checking the maximum length of command line arguments... 98304
#0 112.0         checking how to convert x86_64-pc-linux-musl file names to x86_64-pc-linux-musl format... func_convert_file_noop
#0 112.0         checking how to convert x86_64-pc-linux-musl file names to toolchain format... func_convert_file_noop
#0 112.0         checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
#0 112.0         checking for objdump... objdump
#0 112.0         checking how to recognize dependent libraries... pass_all
#0 112.0         checking for dlltool... no
#0 112.0         checking how to associate runtime and link libraries... printf %s\n
#0 112.0         checking for ar... ar
#0 112.0         checking for archiver @FILE support... @
#0 112.0         checking for strip... strip
#0 112.0         checking for ranlib... ranlib
#0 112.0         checking command to parse /usr/bin/nm -B output from gcc object... ok
#0 112.0         checking for sysroot... no
#0 112.0         checking for a working dd... /bin/dd
#0 112.0         checking how to truncate binary pipes... /bin/dd bs=4096 count=1
#0 112.0         checking for mt... no
#0 112.0         checking if : is a manifest tool... no
#0 112.0         checking how to run the C preprocessor... gcc -E
#0 112.0         checking for ANSI C header files... yes
#0 112.0         checking for sys/types.h... yes
#0 112.0         checking for sys/stat.h... yes
#0 112.0         checking for stdlib.h... yes
#0 112.0         checking for string.h... yes
#0 112.0         checking for memory.h... yes
#0 112.0         checking for strings.h... yes
#0 112.0         checking for inttypes.h... yes
#0 112.0         checking for stdint.h... yes
#0 112.0         checking for unistd.h... yes
#0 112.0         checking for dlfcn.h... yes
#0 112.0         checking for objdir... .libs
#0 112.0         checking if gcc supports -fno-rtti -fno-exceptions... no
#0 112.0         checking for gcc option to produce PIC... -fPIC -DPIC
#0 112.0         checking if gcc PIC flag -fPIC -DPIC works... yes
#0 112.0         checking if gcc static flag -static works... yes
#0 112.0         checking if gcc supports -c -o file.o... yes
#0 112.0         checking if gcc supports -c -o file.o... (cached) yes
#0 112.0         checking whether the gcc linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
#0 112.0         checking whether -lc should be explicitly linked in... no
#0 112.0         checking dynamic linker characteristics... GNU/Linux ld.so
#0 112.0         checking how to hardcode library paths into programs... immediate
#0 112.0         checking whether stripping libraries is possible... yes
#0 112.0         checking if libtool supports shared libraries... yes
#0 112.0         checking whether to build shared libraries... yes
#0 112.0         checking whether to build static libraries... no
#0 112.0         checking for g++... g++
#0 112.0         checking whether we are using the GNU C++ compiler... yes
#0 112.0         checking whether g++ accepts -g... yes
#0 112.0         checking dependency style of g++... gcc3
#0 112.0         checking how to run the C++ preprocessor... g++ -E
#0 112.0         checking for ld used by g++... /usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64
#0 112.0         checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) is GNU ld... yes
#0 112.0         checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
#0 112.0         checking for g++ option to produce PIC... -fPIC -DPIC
#0 112.0         checking if g++ PIC flag -fPIC -DPIC works... yes
#0 112.0         checking if g++ static flag -static works... yes
#0 112.0         checking if g++ supports -c -o file.o... yes
#0 112.0         checking if g++ supports -c -o file.o... (cached) yes
#0 112.0         checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
#0 112.0         checking dynamic linker characteristics... (cached) GNU/Linux ld.so
#0 112.0         checking how to hardcode library paths into programs... immediate
#0 112.0         checking whether g++ supports C++11 features by default... yes
#0 112.0         checking for xapian-config... /usr/bin/xapian-config
#0 112.0         checking /usr/bin/xapian-config works... yes
#0 112.0         checking if /usr/bin/xapian-config version >= 1.4.0... yes (1.4.19)
#0 112.0         checking whether to enable maintainer-specific portions of Makefiles... no
#0 112.0         checking for /root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/bin/python... /root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/bin/python
#0 112.0         checking /root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/bin/python version... 3.11
#0 112.0         Error in sitecustomize; set PYTHONVERBOSE for traceback:
#0 112.0         AssertionError:
#0 112.0         checking for python3 sphinx module... yes
#0 112.0         checking for /usr/local/include/python3.11/Python.h... yes
#0 112.0         checking for directory to install python3 bindings in... /tmp/pip-req-build-8duh76t_/build/bdist.linux-x86_64/wheel
#0 112.0         checking for python3 libraries to link against...
#0 112.0         checking for python3 module extension... Error in sitecustomize; set PYTHONVERBOSE for traceback:
#0 112.0         AssertionError:
#0 112.0         None
#0 112.0         checking for tag for cached compiled scripts... Error in sitecustomize; set PYTHONVERBOSE for traceback:
#0 112.0         AssertionError:
#0 112.0         <string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
#0 112.0         cpython-311
#0 112.0         checking for extension of cached and optimized python3 bytecode... Error in sitecustomize; set PYTHONVERBOSE for traceback:
#0 112.0         AssertionError:
#0 112.0         <string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
#0 112.0         cpython-311.opt-1.pyc
#0 112.0         checking for thread-local storage qualifier... thread_local
#0 112.0         checking if g++ -fvisibility=hidden works... yes
#0 112.0         checking that generated files are newer than configure... done
#0 112.0         configure: creating ./config.status
#0 112.0         config.status: creating Makefile
#0 112.0         config.status: creating doxygen_xml.conf
#0 112.0         config.status: creating xapian-version.h
#0 112.0         config.status: creating python/Makefile
#0 112.0         config.status: creating python/docs/conf.py
#0 112.0         config.status: creating python/version.i
#0 112.0         config.status: creating python3/Makefile
#0 112.0         config.status: creating python3/docs/conf.py
#0 112.0         config.status: creating python3/version.i
#0 112.0         config.status: creating php/Makefile
#0 112.0         config.status: creating php7/Makefile
#0 112.0         config.status: creating java/Makefile
#0 112.0         config.status: creating tcl8/Makefile
#0 112.0         config.status: creating tcl8/pkgIndex.tcl
#0 112.0         config.status: creating csharp/Makefile
#0 112.0         config.status: creating csharp/AssemblyInfo.cs
#0 112.0         config.status: creating ruby/Makefile
#0 112.0         config.status: creating perl/Makefile
#0 112.0         config.status: creating lua/Makefile
#0 112.0         config.status: creating xapian-bindings.spec
#0 112.0         config.status: creating config.h
#0 112.0         config.status: executing depfiles commands
#0 112.0         config.status: executing libtool commands
#0 112.0         
#0 112.0         *** Building bindings for languages: python3
#0 112.0         
#0 112.0         Making clean in .
#0 112.0         make[1]: Entering directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19'
#0 112.0         rm -rf .libs _libs
#0 112.0         rm -f *.lo
#0 112.0         make[1]: Leaving directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19'
#0 112.0         Making clean in python3
#0 112.0         make[1]: Entering directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19/python3'
#0 112.0         test -z "xapian/_xapianNone xapian/__init__.py xapian/__pycache__/__init__.cpython-311.pyc xapian/__pycache__/__init__.cpython-311.opt-1.pyc ./*.pyc " || rm -f xapian/_xapianNone xapian/__init__.py xapian/__pycache__/__init__.cpython-311.pyc xapian/__pycache__/__init__.cpython-311.opt-1.pyc ./*.pyc
#0 112.0         rm -rf .libs _libs
#0 112.0         rmdir xapian/__pycache__
#0 112.0         rmdir: 'xapian/__pycache__': No such file or directory
#0 112.0         make[1]: [Makefile:1300: clean-local] Error 1 (ignored)
#0 112.0         rmdir xapian
#0 112.0         rmdir: 'xapian': No such file or directory
#0 112.0         make[1]: [Makefile:1301: clean-local] Error 1 (ignored)
#0 112.0         rm -rf doctrees docs/html db_test_* dbs_replication
#0 112.0         test -z "_xapian.la" || rm -f _xapian.la
#0 112.0         rm -f ./so_locations
#0 112.0         rm -f *.o
#0 112.0         test -z "smoketest.py.log pythontest.py.log" || rm -f smoketest.py.log pythontest.py.log
#0 112.0         test -z "smoketest.py.trs pythontest.py.trs" || rm -f smoketest.py.trs pythontest.py.trs
#0 112.0         test -z "test-suite.log" || rm -f test-suite.log
#0 112.0         rm -f *.lo
#0 112.0         make[1]: Leaving directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19/python3'
#0 112.0         make  all-recursive
#0 112.0         make[1]: Entering directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19'
#0 112.0         Making all in .
#0 112.0         make[2]: Entering directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19'
#0 112.0         make[2]: Leaving directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19'
#0 112.0         Making all in python3
#0 112.0         make[2]: Entering directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19/python3'
#0 112.0         make  all-am
#0 112.0         make[3]: Entering directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19/python3'
#0 112.0         depbase=`echo xapian_wrap.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
#0 112.0         /bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include/python3.11  -fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized -fvisibility=hidden  -g -O2 -MT xapian_wrap.lo -MD -MP -MF $depbase.Tpo -c -o xapian_wrap.lo xapian_wrap.cc &&\
#0 112.0         mv -f $depbase.Tpo $depbase.Plo
#0 112.0         libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include/python3.11 -fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized -fvisibility=hidden -g -O2 -MT xapian_wrap.lo -MD -MP -MF .deps/xapian_wrap.Tpo -c xapian_wrap.cc  -fPIC -DPIC -o .libs/xapian_wrap.o
#0 112.0         /bin/sh ../libtool  --tag=CXX   --mode=link g++ -fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized -fvisibility=hidden  -g -O2 -avoid-version -module -shrext "None"   -o _xapian.la -rpath /tmp/pip-req-build-8duh76t_/build/bdist.linux-x86_64/wheel/xapian xapian_wrap.lo -lxapian -lstdc++
#0 112.0         libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/crtbeginS.o  .libs/xapian_wrap.o   -lxapian -L/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1 -L/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../.. -lstdc++ -lm -lssp_nonshared -lc -lgcc_s /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/crtendS.o /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../lib/crtn.o  -g -O2   -Wl,-soname -Wl,_xapianNone -o .libs/_xapianNone
#0 112.0         libtool: link: ( cd ".libs" && rm -f "_xapian.la" && ln -s "../_xapian.la" "_xapian.la" )
#0 112.0         .././install-sh -c -d xapian
#0 112.0         cp `test -f xapian.py || echo './'`xapian.py xapian/__init__.py
#0 112.0         .././install-sh -c -d xapian
#0 112.0         /bin/sh ../libtool --config > libtoolconfig.tmp
#0 112.0         . ./libtoolconfig.tmp; cp $objdir/_xapianNone xapian
#0 112.0         rm -f libtoolconfig.tmp
#0 112.0         /root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/bin/python -c 'import os;os.chdir("xapian");import _xapian'
#0 112.0         Error in sitecustomize; set PYTHONVERBOSE for traceback:
#0 112.0         AssertionError:
#0 112.0         Traceback (most recent call last):
#0 112.0           File "<string>", line 1, in <module>
#0 112.0         ModuleNotFoundError: No module named '_xapian'
#0 112.0         make[3]: *** [Makefile:1283: xapian/__pycache__/__init__.cpython-311.pyc] Error 1
#0 112.0         make[3]: Leaving directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19/python3'
#0 112.0         make[2]: *** [Makefile:682: all] Error 2
#0 112.0         make[2]: Leaving directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19/python3'
#0 112.0         make[1]: *** [Makefile:521: all-recursive] Error 1
#0 112.0         make[1]: Leaving directory '/tmp/pip-req-build-8duh76t_/build/temp.linux-x86_64-cpython-311/xapian-bindings-1.4.19'
#0 112.0         make: *** [Makefile:443: all] Error 2
#0 112.0         https://oligarchy.co.uk/xapian/1.4.19/xapian-bindings-1.4.19.tar.xz
#0 112.0         {'Date': 'Sun, 06 Nov 2022 02:15:37 GMT', 'Server': 'Apache/2.4.38', 'Last-Modified': 'Fri, 31 Dec 2021 23:49:32 GMT', 'ETag': '"115bbc-5d479d29042fc"', 'Accept-Ranges': 'bytes', 'Content-Length': '1137596', 'X-Frame-Options': 'sameorigin', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'application/x-xz'}
#0 112.0         {'xapian-bindings-1.4.19'}
#0 112.0         Traceback (most recent call last):
#0 112.0           File "/root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
#0 112.0             main()
#0 112.0           File "/root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
#0 112.0             json_out['return_val'] = hook(**hook_input['kwargs'])
#0 112.0                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 112.0           File "/root/.cache/pypoetry/virtualenvs/codex-9TtSrW0h-py3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
#0 112.0             return _build_backend().build_wheel(wheel_directory, config_settings,
#0 112.0                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 412, in build_wheel
#0 112.0             return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#0 112.0                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
#0 112.0             self.run_setup()
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 484, in run_setup
#0 112.0             self).run_setup(setup_script=setup_script)
#0 112.0                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
#0 112.0             exec(code, locals())
#0 112.0           File "<string>", line 333, in <module>
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
#0 112.0             return distutils.core.setup(**attrs)
#0 112.0                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 112.0             return run_commands(dist)
#0 112.0                    ^^^^^^^^^^^^^^^^^^
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 112.0             dist.run_commands()
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
#0 112.0             self.run_command(cmd)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
#0 112.0             super().run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#0 112.0             cmd_obj.run()
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 359, in run
#0 112.0             self.run_command("install")
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
#0 112.0             self.distribution.run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
#0 112.0             super().run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#0 112.0             cmd_obj.run()
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
#0 112.0             return orig.install.run(self)
#0 112.0                    ^^^^^^^^^^^^^^^^^^^^^^
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 709, in run
#0 112.0             self.run_command(cmd_name)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
#0 112.0             self.distribution.run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
#0 112.0             super().run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#0 112.0             cmd_obj.run()
#0 112.0           File "<string>", line 239, in run
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
#0 112.0             self.distribution.run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
#0 112.0             super().run_command(command)
#0 112.0           File "/tmp/pip-build-env-m8md0zs_/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#0 112.0             cmd_obj.run()
#0 112.0           File "<string>", line 208, in run
#0 112.0           File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
#0 112.0             raise CalledProcessError(retcode, cmd)
#0 112.0         subprocess.CalledProcessError: Command '['make', 'clean', 'all']' returned non-zero exit status 2.
#0 112.0         [end of output]
```

**Comment by ajslater** [comment]
This seems to have been some local config issue. Seems to have resolved as of two weeks ago.
